version: '3'
services:
  nginx:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"  # Nginx by default serves on port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx config, if needed
    restart: unless-stopped
